# Constants

# Serial message formatting
PREFIX = "$"
SUFFIX = "!"
ENCODING = "utf-8"

BAUD_RATE = 115200 # Ensure this matches the flight computer's baud rate

# communication messages
HANDSHAKE_MESSAGE = "START_TRANSFER"
ACK_MESSAGE = "TRANSFER_ACK"
END_OF_TRANSMISSION_MESSAGE = "END_OF_TRANSMISSION"
END_OF_TRANSMISSION_ACK = "END_OF_TRANSMISSION_ACK"
FILE_COPY_MESSAGE = "FILE_ALREADY_RECEIVED"
ALL_FILES_SENT = "ALL_FILES_SENT"
ALL_FILES_SENT_ACK = "ALL_FILES_SENT_ACK"
REQUEST_FILE_DOWNLOAD = "REQUEST_FILE_DOWNLOAD"
CANCEL_MSG_REQUEST = "EXIT_PROGRAM"

# modes
GO_TO_STANDBY = "mode:0"
GO_TO_READ = "mode:1"
GO_TO_PURGE = "mode:2"
GO_TO_LOGGING = "mode:3"
GO_TO_FINS = "mode:4"
MODE_MSG_ARRAY = [GO_TO_STANDBY, GO_TO_READ, GO_TO_PURGE, GO_TO_LOGGING, GO_TO_FINS]

# Directory and file naming
OUTPUT_DIRECTORY = "flightData"
LOG_FOLDER = "logFiles"
DATA_FOLDER = "dataFiles"
MISC_FOLDER = "miscFiles"
DEFAULT_FILE_PREFIX = "flight_data_"
LOG_FILE_PREFIX = "log"
DATA_FILE_PREFIX = "data"