#ifndef CONFIG_KEYS_HPP
#define CONFIG_KEYS_HPP

#define ALTITUDE_BUFFER_PERIOD 0x00
#define G_OFFSET 0x01
#define LAUNCH_VEL_THRESHOLD 0x02
#define LAUNCH_ACC_THRESHOLD 0x03
#define APOGEE_TIMER 0x04
#define LANDING_VEL_THRESHOLD 0x05
#define BOOTUP_MODE 0x06
#define DUAL_DEPLOY 0x07
#define DROGUE_DELAY 0x08
#define MAIN_DELAY 0x09
#define MAIN_DEPLOYMENT_ALT 0x0A

#endif // CONFIG_KEYS_HPP
