#ifndef CONFIG_KEYS_HPP
#define CONFIG_KEYS_HPP

#define ALTITUDE_BUFFER_PERIOD 0x00
#define G_OFFSET 0x05
#define RECURSIVE_CONSTANT 0x06
#define LAUNCH_VEL_THRESHOLD 0x07
#define LAUNCH_ACC_THRESHOLD 0x08
#define APOGEE_TIMER 0x09
#define LANDING_VEL_THRESHOLD 0x0A
#define EPSILON 0x0B

#endif // CONFIG_KEYS_HPP
