#ifndef CONFIG_KEYS_HPP
#define CONFIG_KEYS_HPP

#define ALTITUDE_BUFFER_PERIOD 0x00
#define G_OFFSET 0x01
#define LAUNCH_VEL_THRESHOLD 0x02
#define LAUNCH_ACC_THRESHOLD 0x03
#define APOGEE_TIMER 0x04
#define LANDING_VEL_THRESHOLD 0x05

#endif // CONFIG_KEYS_HPP
