# Constants
HANDSHAKE_MESSAGE = "START_TRANSFER\n"
ACK_MESSAGE = "TRANSFER_ACK"
END_OF_TRANSMISSION_MESSAGE = "END_OF_TRANSMISSION"
END_OF_TRANSMISSION_ACK = "END_OF_TRANSMISSION_ACK\n"
FILE_COPY_MESSAGE = "FILE_ALREADY_RECEIVED\n"
ALL_FILES_SENT = "ALL_FILES_SENT"
ALL_FILES_SENT_ACK = "ALL_FILES_SENT_ACK\n"
REQUEST_FILE_DOWNLOAD = "REQUEST_FILE_DOWNLOAD\n"

# modes
GO_TO_STANDBY = "mode:0\n"
GO_TO_READ = "mode:1\n"
GO_TO_PURGE = "mode:2\n"
GO_TO_LOGGING = "mode:3\n"
GO_TO_FINS = "mode:4\n"
MODE_MSG_ARRAY = [GO_TO_STANDBY, GO_TO_READ, GO_TO_PURGE, GO_TO_LOGGING, GO_TO_FINS]

# Directory and file naming
OUTPUT_DIRECTORY = "flightData"
LOG_FOLDER = "logFiles"
DATA_FOLDER = "dataFiles"
MISC_FOLDER = "miscFiles"
DEFAULT_FILE_PREFIX = "flight_data_"
LOG_FILE_PREFIX = "log"
DATA_FILE_PREFIX = "data"